"use client";

import clsx from "clsx";

/**
 * GeneratingBlock (Primitive) — placeholder for a dashboard section whose
 * content is still being generated by the agent (the "living" acquainted
 * screen). Renders stacked shimmer lines that read as text, plus an optional
 * status row beneath ("Compiling what Trovio sees in your content…").
 *
 * Presentation-only: no card/border chrome — it sits inside sections, so the
 * surrounding layout provides spacing and any hairline rules.
 */
export interface GeneratingBlockProps {
  /** Short status line shown under the shimmer. Omitted when absent. */
  message?: string;
  /** Number of shimmer text lines. Default 3. */
  lines?: number;
  className?: string;
}

/** Varied widths so the shimmer reads as text, repeating every three lines. */
const LINE_WIDTHS = ["100%", "92%", "66%"];

export function GeneratingBlock({
  message,
  lines = 3,
  className,
}: GeneratingBlockProps) {
  return (
    <div className={clsx("space-y-4", className)}>
      <div aria-hidden className="space-y-2.5">
        {Array.from({ length: lines }, (_, i) => (
          <div
            key={i}
            className="h-4 animate-pulse rounded bg-trovio-light-text/10 dark:bg-trovio-dark-text/10"
            style={{ width: LINE_WIDTHS[i % LINE_WIDTHS.length] }}
          />
        ))}
      </div>
      {message && (
        <div className="flex items-center gap-2">
          <span className="size-1.5 shrink-0 animate-pulse rounded-full bg-trovio-primary" />
          <p className="text-caption text-trovio-light-text-muted dark:text-trovio-dark-text-muted">
            {message}
          </p>
        </div>
      )}
    </div>
  );
}
